# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18.2

# Java version used to compile the mod and required at runtime.
java_version=25

# Mod Properties
# The published version is "<mod_version>+<minecraft_version>".
mod_version=1.0.0
group=com.urntt

# Dependencies
fabric_api_version=0.161.0+26.3
modmenu_version=21.0.0
